parameters:
#    lanzadera_organization.example.class: Lanzadera\OrganizationBundle\Example

services:
#    lanzadera_organization.example:
#        class: %lanzadera_organization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lanzadera.admin.organization:
        class: Lanzadera\OrganizationBundle\Admin\OrganizationAdmin
        arguments: [~, Lanzadera\OrganizationBundle\Entity\Organization, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administración, label: Organizaciones}
