parameters:
    lanzadera.admin.organization.class: Lanzadera\OrganizationBundle\Admin\OrganizationAdmin
    lanzadera.entity.organization.class: Lanzadera\OrganizationBundle\Entity\Organization
    lanzadera.organization.admin.group: product.admin.group
services:
    lanzadera.admin.organization:
        class: %lanzadera.admin.organization.class%
        arguments: [~, %lanzadera.entity.organization.class%, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.organization.admin.group%, label: organization.admin.label}
        calls:
            - [ setTemplate, [edit, LanzaderaCommentBundle:CRUD:edit.html.twig]]
            - [ setTemplate, [inner_list_row, LanzaderaOrganizationBundle:CRUD:inner_list_row.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
