parameters:
    lanzadera.organization.admin.group: product.admin.group
services:
#    lanzadera_organization.example:
#        class: %lanzadera_organization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lanzadera.admin.organization:
        class: Lanzadera\OrganizationBundle\Admin\OrganizationAdmin
        arguments: [~, Lanzadera\OrganizationBundle\Entity\Organization, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.organization.admin.group%, label: organization.admin.label}
