parameters:
#    lanzadera_classification.example.class: Lanzadera\ClassificationBundle\Example
     lanzadera.taxonomy.admin.group: product.admin.group

services:
#    lanzadera_classification.example:
#        class: %lanzadera_classification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lanzadera.admin.category:
        class: Lanzadera\TaxonomyBundle\Admin\CategoryAdmin
        arguments: [~, Lanzadera\TaxonomyBundle\Entity\Taxon, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.taxonomy.admin.group%, label: category.admin.label}
    lanzadera.admin.tag:
        class: Lanzadera\TaxonomyBundle\Admin\TagAdmin
        arguments: [~, Lanzadera\TaxonomyBundle\Entity\Taxon, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.taxonomy.admin.group%, label: tag.admin.label}

