parameters:
#    lanzadera_classification.example.class: Lanzadera\ClassificationBundle\Example

services:
#    lanzadera_classification.example:
#        class: %lanzadera_classification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lanzadera.admin.taxon:
        class: Lanzadera\TaxonomyBundle\Admin\TaxonAdmin
        arguments: [~, Lanzadera\TaxonomyBundle\Entity\Taxon, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Gestión de productos, label: Categorías}
    lanzadera.admin.taxonomy:
        class: Lanzadera\TaxonomyBundle\Admin\TaxonomyAdmin
        arguments: [~, Lanzadera\TaxonomyBundle\Entity\Taxonomy, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Gestión de productos, label: Etiquetas}

