Lanzadera\TaxonomyBundle\Entity\Taxon:
    properties:
        name:
            - NotBlank:
                message: category.name.not_blank


Lanzadera\TaxonomyBundle\Entity\Taxonomy:
    properties:
        name:
            - NotBlank:
                message: tag.name.not_blank


