lanzadera_api_product_index:
    pattern: /products
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.product:indexAction
lanzadera_api_product_show:
    pattern: /products/{id}
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.product:showAction
        _sylius:
            criteria: { status: approved }