parameters:
#    lanzadera_product.example.class: Lanzadera\ProductBundle\Example

services:
#    lanzadera_product.example:
#        class: %lanzadera_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lanzadera.admin.product:
        class: Lanzadera\ProductBundle\Admin\ProductAdmin
        arguments: [~, Lanzadera\ProductBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administración, label: Productos}
