parameters:
#    lanzadera_product.example.class: Lanzadera\ProductBundle\Example

services:
#    lanzadera_product.example:
#        class: %lanzadera_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
