parameters:
    lanzadera.admin.product.class: Lanzadera\ProductBundle\Admin\ProductAdmin
    lanzadera.entity.product.class: Lanzadera\ProductBundle\Entity\Product
    lanzadera.form.type.status.class: Lanzadera\ProductBundle\Form\Type\StatusType

services:
    lanzadera.admin.product:
        class: %lanzadera.admin.product.class%
        arguments: [~, %lanzadera.entity.product.class%, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: product.admin.group, label: product.admin.label }

    lanzadera.form.type.status:
        class: %lanzadera.form.type.status.class%
        tags:
            - { name: form.type, alias: status }