bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              %kernel.cache_dir%/hateoas

fos_rest:
    param_fetcher_listener: true
    body_listener:          true
    body_converter:
        enabled: true
        validate: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    format_listener:
        rules:
            - { path: '^/api/thread', priorities: [ 'html'], fallback_format: html }
            - { path: '^/api', priorities: [ json, xml ], fallback_format: json }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html }
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        empty_content:        204
        exception_wrapper_handler:  FOS\RestBundle\View\ExceptionWrapperHandler
        serialize_null:       false
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        default_engine: twig

nelmio_api_doc: ~

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600