security:
    access_decision_manager:
        strategy: unanimous

    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_LANZADERA_ADMIN_ADMIN:
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
        ROLE_LANZADERA_ADMIN_STAFF:
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_ENABLED
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_DELETE
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_EXPORT
            - ROLE_LANZADERA_ADMIN_PRODUCT_STATUS
            - ROLE_LANZADERA_ADMIN_PRODUCT_DELETE
            - ROLE_LANZADERA_ADMIN_PRODUCT_EXPORT
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_EDIT
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_EDIT
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_CREATE
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_DELETE
            - ROLE_LANZADERA_ADMIN_CLASSIFICATION_LIST
            - ROLE_LANZADERA_ADMIN_CLASSIFICATION_VIEW
            - ROLE_LANZADERA_ADMIN_CLASSIFICATION_EDIT
            - ROLE_LANZADERA_ADMIN_CLASSIFICATION_CREATE
            - ROLE_LANZADERA_ADMIN_CLASSIFICATION_DELETE
            - ROLE_LANZADERA_ADMIN_CRITERION_LIST
            - ROLE_LANZADERA_ADMIN_CRITERION_VIEW
            - ROLE_LANZADERA_ADMIN_CRITERION_EDIT
            - ROLE_LANZADERA_ADMIN_CRITERION_CREATE
            - ROLE_LANZADERA_ADMIN_CRITERION_DELETE
            - ROLE_LANZADERA_ADMIN_INDICATOR_LIST
            - ROLE_LANZADERA_ADMIN_INDICATOR_VIEW
            - ROLE_LANZADERA_ADMIN_INDICATOR_EDIT
            - ROLE_LANZADERA_ADMIN_INDICATOR_CREATE
            - ROLE_LANZADERA_ADMIN_INDICATOR_DELETE
        ROLE_LANZADERA_ADMIN_OPERATOR:
            - ROLE_LANZADERA_ADMIN_PRODUCT_LIST
            - ROLE_LANZADERA_ADMIN_PRODUCT_VIEW
            - ROLE_LANZADERA_ADMIN_PRODUCT_EDIT
            - ROLE_LANZADERA_ADMIN_PRODUCT_CREATE
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_LIST
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_VIEW
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_EDIT
            - ROLE_LANZADERA_ADMIN_ORGANIZATION_CREATE
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_LIST
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_VIEW
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_LIST
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_VIEW
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_EDIT
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_CREATE
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_DELETE
        ROLE_ADMIN:       [ROLE_STAFF, ROLE_LANZADERA_ADMIN_ADMIN]
        ROLE_STAFF:       [ROLE_OPERATOR, ROLE_LANZADERA_ADMIN_STAFF]
        ROLE_OPERATOR:    [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_LANZADERA_ADMIN_OPERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                key:  "%secret%"
                lifetime: 3153600
                path: /
                domain: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
