lanzadera_api_organization_index:
    pattern: /organizations
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.organization:indexAction
        _sylius:
            paginate: 9
            sorting:
                name: asc
            criteria:
                enabled: true

lanzadera_api_organization_product_index:
    pattern: /organizations/{slug}/products
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.product:indexAction
        _sylius:
            paginate: 9
            method: findAllAvailableProductsByOrganizationSlug
            arguments: [ $slug ]
            sorting:
                name: asc

lanzadera_api_organization_show:
    pattern: /organizations/{slug}
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.organization:showAction
        _sylius:
            paginate: 9
            criteria:
                slug: $slug
                enabled: true