parameters:
    lanzadera.classification.admin.group: classification.admin.group
    lanzadera.model.indicator.class: Lanzadera\ClassificationBundle\Entity\Indicator

services:
    lanzadera.admin.classification:
        class: Lanzadera\ClassificationBundle\Admin\ClassificationAdmin
        arguments: [~, Lanzadera\ClassificationBundle\Entity\Classification, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.classification.admin.group%, label: classificacion.admin.label}

    lanzadera.admin.criterion:
        class: Lanzadera\ClassificationBundle\Admin\CriterionAdmin
        arguments: [~, Lanzadera\ClassificationBundle\Entity\Criterion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.classification.admin.group%, label: criterion.admin.label}

    lanzadera.admin.indicator:
        class: Lanzadera\ClassificationBundle\Admin\IndicatorAdmin
        arguments: [~, Lanzadera\ClassificationBundle\Entity\Indicator, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: %lanzadera.classification.admin.group%, label: indicator.admin.label, show_in_dashboard: false}

    lanzadera.form.type.lanzadera_indicator:
        class: Lanzadera\ClassificationBundle\Form\Type\IndicatorType
        arguments: [@doctrine.orm.entity_manager, @ladybug]
        tags:
            - { name: form.type, alias: lanzadera_indicator }

    lanzadera.form.type.choice_type_extension:
            class: Lanzadera\ClassificationBundle\Form\Extension\ChoiceTypeExtension
            tags:
                - { name: form.type_extension, alias: choice }
