parameters:
    lanzadera.admin.classification.class: Lanzadera\ClassificationBundle\Admin\ClassificationAdmin
    lanzadera.admin.criterion.class: Lanzadera\ClassificationBundle\Admin\CriterionAdmin
    lanzadera.admin.indicator.class: Lanzadera\ClassificationBundle\Admin\IndicatorAdmin
    lanzadera.entity.classification.class: Lanzadera\ClassificationBundle\Entity\Classification
    lanzadera.entity.criterion.class: Lanzadera\ClassificationBundle\Entity\Criterion
    lanzadera.entity.indicator.class: Lanzadera\ClassificationBundle\Entity\Indicator
    lanzadera.entity.listener.classification.class: Lanzadera\ClassificationBundle\EventListener\ClassificationListener
    lanzadera.entity.listener.indicator.class: Lanzadera\ClassificationBundle\EventListener\IndicatorListener
    lanzadera.form.extension.choice_type_extention.class: Lanzadera\ClassificationBundle\Form\Extension\ChoiceTypeExtension
    lanzadera.form.transformer.array_to_indicators.class: Lanzadera\ClassificationBundle\Form\DataTransformer\ArrayToIndicatorsTransform
    lanzadera.form.type.criterion.class: Lanzadera\ClassificationBundle\Form\Type\CriterionType
    lanzadera.form.type.organization_indicator.class: Lanzadera\ClassificationBundle\Form\Type\OrganizationIndicatorType
    lanzadera.form.type.product_indicator.class: Lanzadera\ClassificationBundle\Form\Type\ProductIndicatorType

services:
    lanzadera.admin.classification:
        class: %lanzadera.admin.classification.class%
        arguments: [~, %lanzadera.entity.classification.class%, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: classification.admin.group, label: classificacion.admin.label}

    lanzadera.admin.criterion:
        class: %lanzadera.admin.criterion.class%
        arguments: [~, %lanzadera.entity.criterion.class%, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: classification.admin.group, label: criterion.admin.label}

    lanzadera.admin.indicator:
        class: %lanzadera.admin.indicator.class%
        arguments: [~, %lanzadera.entity.indicator.class%, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: classification.admin.group, label: indicator.admin.label, show_in_dashboard: false}

    lanzadera.form.type.criterion:
        class: %lanzadera.form.type.criterion.class%
        tags:
            - { name: form.type, alias: criterion_type }

    lanzadera.form.type.lanzadera_indicator:
        class: %lanzadera.form.type.organization_indicator.class%
        arguments: [@lanzadera.repository.criterion, @lanzadera.form.transformer.array_to_indicators]
        tags:
            - { name: form.type, alias: organization_indicator }

    lanzadera.form.type.product_indicator:
        class: %lanzadera.form.type.product_indicator.class%
        arguments: [@lanzadera.repository.criterion, @lanzadera.form.transformer.array_to_indicators]
        tags:
            - { name: form.type, alias: product_indicator }

    lanzadera.form.extension.choice_type_extension:
        class: %lanzadera.form.extension.choice_type_extention.class%
        tags:
            - { name: form.type_extension, alias: choice }

    lanzadera.form.transformer.array_to_indicators:
        class: %lanzadera.form.transformer.array_to_indicators.class%
        arguments: [@lanzadera.repository.indicator]

    lanzadera.entity.listener.indicator:
        class: %lanzadera.entity.listener.indicator.class%
        tags:
            - { name: doctrine.orm.entity_listener, entity_manager: default }

    lanzadera.entity.listener.classification:
        class: %lanzadera.entity.listener.classification.class%
        tags:
            - { name: doctrine.orm.entity_listener, entity_manager: default }