parameters:

    lanzadera.form.extension.choice_type_extention.class: Lanzadera\ClassificationBundle\Form\Extension\ChoiceTypeExtension
    lanzadera.form.type.certificate.class: Lanzadera\ClassificationBundle\Form\Type\CertificateType
    lanzadera.form.type.criterion.class: Lanzadera\ClassificationBundle\Form\Type\CriterionType
    lanzadera.form.type.organization_indicator.class: Lanzadera\ClassificationBundle\Form\Type\OrganizationIndicatorType
    lanzadera.form.type.product_indicator.class: Lanzadera\ClassificationBundle\Form\Type\ProductIndicatorType

services:


    lanzadera.form.type.certificate:
        class: %lanzadera.form.type.certificate.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: certificate }

    lanzadera.form.type.criterion:
        class: %lanzadera.form.type.criterion.class%
        tags:
            - { name: form.type, alias: criterion_type }

    lanzadera.form.type.organization_indicator:
        class: %lanzadera.form.type.organization_indicator.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: organization_indicator }

    lanzadera.form.type.product_indicator:
        class: %lanzadera.form.type.product_indicator.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: product_indicator }

    lanzadera.form.extension.choice_type_extension:
        class: %lanzadera.form.extension.choice_type_extention.class%
        tags:
            - { name: form.type_extension, alias: choice }

