parameters: ~

services:

#    lanzadera.repository.category:
#        class: AppBundle\Doctrine\ORM\TaxonRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\Taxon']

    lanzadera.repository.certificate:
        class: AppBundle\Doctrine\ORM\CertificateRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Certificate']

    lanzadera.repository.classification:
        class: AppBundle\Doctrine\ORM\ClassificationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Classification']

    lanzadera.repository.criterion:
        class: AppBundle\Doctrine\ORM\CriterionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Criterion']

    lanzadera.repository.group:
        class: AppBundle\Doctrine\ORM\GroupRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Group']

    lanzadera.repository.indicator:
        class: AppBundle\Doctrine\ORM\IndicatorRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Indicator']

    lanzadera.repository.media:
        class: AppBundle\Doctrine\ORM\MediaRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Application\Sonata\MediaBundle\Entity\Media']

    lanzadera.repository.organization:
        class: AppBundle\Doctrine\ORM\OrganizationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Organization']

    lanzadera.repository.product:
        class: AppBundle\Doctrine\ORM\ProductRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Product']

#    lanzadera.repository.tag:
#        class: AppBundle\Doctrine\ORM\TaxonRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\Taxon']
#
#    lanzadera.repository.taxon:
#        class: AppBundle\Doctrine\ORM\TaxonRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\Taxon']
#
#    lanzadera.repository.taxonomy:
#        class: AppBundle\Doctrine\ORM\TaxonomyRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\Taxonomy']

    lanzadera.repository.user:
        class: AppBundle\Doctrine\ORM\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\User']

    lanzadera.core.backend.consumer:
        class: AppBundle\Consumer\LanzaderaBackendConsumer
        arguments: [@logger, @doctrine.orm.entity_manager]
        tags:
            - { name: sonata.notification.consumer, type: backend }