parameters: ~

services:

    lanzadera.repository.category:
        class: AppBundle\Doctrine\ORM\TaxonRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Taxon']

    lanzadera.repository.certificate:
        class: AppBundle\Doctrine\ORM\CertificateRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Certificate']

    lanzadera.repository.classification:
        class: AppBundle\Doctrine\ORM\ClassificationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Classification']

    lanzadera.repository.criterion:
        class: AppBundle\Doctrine\ORM\CriterionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Criterion']

    lanzadera.repository.group:
        class: Lanzadera\CoreBundle\Doctrine\ORM\GroupRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Lanzadera\CoreBundle\Entity\Group']

    lanzadera.repository.indicator:
        class: AppBundle\Doctrine\ORM\IndicatorRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Indicator']

    lanzadera.repository.media:
        class: Lanzadera\AppBundle\Doctrine\ORM\MediaRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Application\Sonata\MediaBundle\Entity\Media']

    lanzadera.repository.organization:
        class: Lanzadera\CoreBundle\Doctrine\ORM\OrganizationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Lanzadera\OrganizationBundle\Entity\Organization']

    lanzadera.repository.product:
        class: Lanzadera\CoreBundle\Doctrine\ORM\ProductRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Lanzadera\ProductBundle\Entity\Product']

    lanzadera.repository.tag:
        class: AppBundle\Doctrine\ORM\TaxonRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Taxon']

    lanzadera.repository.taxon:
        class: AppBundle\Doctrine\ORM\TaxonRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Taxon']

    lanzadera.repository.taxonomy:
        class: AppBundle\Doctrine\ORM\TaxonomyRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Taxonomy']

    lanzadera.repository.user:
        class: Lanzadera\CoreBundle\Doctrine\ORM\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['Lanzadera\CoreBundle\Entity\User']