lanzadera_api_media_show:
    pattern: /medias/{id}
    methods: [GET]
    defaults:
        _controller: lanzadera.controller.media:showAction
        _sylius:
            criteria: { enabled: true }